"""inital migrate

Revision ID: b606ea22991
Revises: None
Create Date: 2014-09-29 08:18:14.148819

"""

# revision identifiers, used by Alembic.
revision = 'b606ea22991'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=160), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('arena', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('added_on', sa.DateTime(), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=True),
    sa.Column('isdeleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('secret_hash', sa.String(length=128), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=True),
    sa.Column('isdeleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscribers_email', 'subscribers', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscribers_email', 'subscribers')
    op.drop_table('subscribers')
    op.drop_table('contests')
    ### end Alembic commands ###
